export const HANDLE_MIN = 1;
export const HANDLE_MAX = 64;
export const HANDLE_REGEX = /^[A-Za-z0-9._-]+$/;

export const ROLE_LOCAL_PARTS = new Set([
  "admin",
  "administrator",
  "abuse",
  "billing",
  "contact",
  "devops",
  "hello",
  "help",
  "hostmaster",
  "hr",
  "info",
  "jobs",
  "legal",
  "mail",
  "marketing",
  "media",
  "noc",
  "noreply",
  "no-reply",
  "office",
  "ops",
  "postmaster",
  "press",
  "privacy",
  "root",
  "sales",
  "security",
  "support",
  "team",
  "webmaster",
]);

export const DKIM_SELECTORS = [
  "google",
  "selector1",
  "selector2",
  "k1",
  "s1",
  "s2",
  "default",
  "dkim",
  "mail",
  "protonmail",
  "protonmail2",
  "protonmail3",
  "fm1",
  "fm2",
  "fm3",
  "s1024",
  "s2048",
  "ctct1",
  "ctct2",
  "everlytickey1",
  "everlytickey2",
  "sm",
  "smtp",
  "mx",
  "scph1220",
];

export const LOGIN_PATH_HINTS = [
  "/login",
  "/signin",
  "/sign-in",
  "/signup",
  "/sign-up",
  "/register",
  "/explore",
  "/discover",
  "/home",
  "/welcome",
  "/accounts/login",
  "/users/sign_in",
  "/session/new",
  "/auth/login",
];

export const WAF_BODY_HINTS = [
  "captcha",
  "hcaptcha",
  "recaptcha",
  "cf-ray",
  "cf-challenge",
  "attention required",
  "access denied",
  "request blocked",
  "forbidden",
  "checking your browser",
  "just a moment",
  "enable javascript and cookies",
  "making sure you're not a bot",
  "making sure you&#39;re not a bot",
  "are you a robot",
  "akamai",
  "incapsula",
  "sucuri",
  "ddos-guard",
  "blocked by",
  "why have i been blocked",
  "cloudflare",
];

export const WAF_HEADER_HINTS = [
  "cf-mitigated",
  "cf-chl-bypass",
];

export const AUTHORIZED_USE =
  "Umbra is a public-OSINT workstation. Run it only against identifiers you are authorized to investigate. It never sends SMTP or password-reset mail to a subject.";
